version: '3'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: delos
      MYSQL_DATABASE: delos_db
      MYSQL_USER: delos
      MYSQL_PASSWORD: delos
    container_name: Delos-DB
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Delos-Server
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: ["./connect-db.sh", "db", "3306", "./server"]